### ISSUE TITLE
Docker Stack multiple compose file

### ISSUE THREAD

**Issue by rushsteve1** [CarmeLabs/carme#14]
So I have run into a bit of a speedbump and I want everyone's opinion on what the best way to fix it is. As of now `docker stack deploy` does not support multiple compose files. This means that deploying from our collection of compose files is more tricky. The options to solve this are:
1. Using the external `docker-compose` generate a bundle file and load that. This requires the user to have `docker-compose` installed, and bundle files are apparently not very good or well supported.
2. Create a series of stacks, one for each compose file. This decreases re-usability and pollutes the namespace.
3. Merge all the compose files into one larger YAML file and deploy the stack with that. Merging might cause issues.
I personally am leaning toward 3 but I want some other opinions.

**Comment by jkuruzovich** [comment]
@rushsteve1 I think that this problem is the same one that I've been addressing for the `launchfile.yaml` and #3 is the solution I chose.  For the command to add a app I was loading the `launchfile.yaml`, appending the contents of the <packagelaunchfile>.yaml, and writing the output.  The only thing I potentially see as an issue could be the formatting.  See the `self.append_launch_file` function.

**Comment by rushsteve1** [comment]
The basic merge functionality has been complete but the unittest system needs a some work before so that merging can be tested.

**Comment by rushsteve1** [comment]
So my current issue is that when merging there are a lot of newlines interpreted as literal '\n'. I am not sure if this is an issue with the unit test or the merge, but some help would be greatly appreciated.

**Comment by jkuruzovich** [comment]
I was going to suggest you put in an issue!
